### ISSUE TITLE
Requesting Attachments of Documents 

### ISSUE THREAD

**Issue by LearnAutomationOnline** [Arulprasath36/WhatsUp_Development#10]
Dear Arulprasath,

It would be great if the app is capable of attaching the documents as well. Kindly add this feature.

**Comment by Arulprasath36** [comment]
Dear LAO, Thanks for suggesting this feature. We will add and let you know.

**Comment by Arulprasath36** [comment]
Dear LAO, Thanks for your valuable suggestions. This feature is going to make our product great.
