### ISSUE TITLE
Requesting Attachments of file 

### ISSUE THREAD

**Issue by boopal1352** [Arulprasath36/WhatsUp_Development#12]
Hi Arul 

I have attached feature file for your Watsapp_Development 
[Demo 2.txt](https://github.com/Arulprasath36/WhatsUp_Development/files/3032573/Demo.2.txt)

**Comment by Arulprasath36** [comment]
Hi Boopal1352,

thanks for bringing this issue to my notice with detailed document. :P Will look into this.
